In [2]:
print("Hello Jupyter")

Hello Jupyter


In [5]:
import numpy as np

In [4]:
py_list = [1,2,3,4,5,6,7,8,9]

In [6]:
#numpy array
np_array = np.array(py_list)

In [7]:
print(type(np_array))

<class 'numpy.ndarray'>


In [8]:
print(np_array)

[1 2 3 4 5 6 7 8 9]


In [15]:
np_array = np_array.reshape(3,3)

In [16]:
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
sayilar = np.arange(1,10)
print(sayilar)

[1 2 3 4 5 6 7 8 9]


In [22]:
sayilar = np.arange(5,101,5)
sayilar = sayilar.reshape(5,4)
print(sayilar)

[[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]


In [25]:
sifirlar = np.zeros(10)

In [26]:
print(sifirlar)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
birler = np.ones(10)

In [28]:
print(birler)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
araliktakiler = np.linspace(0,100,5)
print(araliktakiler)

[  0.  25.  50.  75. 100.]


In [37]:
rastgele_sayilar = np.random.randint(0,100)

In [38]:
print(rastgele_sayilar)

43


In [40]:
ondalikli = np.random.rand(5)
print(ondalikli)

[0.17915609 0.52713833 0.9496801  0.2986889  0.10316875]


In [41]:
print(sayilar)

[[  5  10  15  20]
 [ 25  30  35  40]
 [ 45  50  55  60]
 [ 65  70  75  80]
 [ 85  90  95 100]]


In [44]:
sutun_toplamlari = sayilar.sum(axis=0)
print(sutun_toplamlari)

[225 250 275 300]


In [45]:
satilar_toplamlari = sayilar.sum(axis=1)
print(satilar_toplamlari)

[ 50 130 210 290 370]


In [50]:
print(sayilar.max())   #Listedeki en büyük sayı

100


In [51]:
print(sayilar.mean())   #Listedeki sayıların ortalaması

52.5


In [52]:
print(sayilar.argmax())   #Listedeki en büyük sayının indeksi

19


In [53]:
print(sayilar.argmin())   #Listedeki en küçük sayının indeksi

0
